---
- name: Update apt cache & upgrade all packages
  apt: update_cache=yes upgrade=full

- name: Set cloud-init config to preserve hostname
  lineinfile:
    "dest=/etc/cloud/cloud.cfg
    create=no
    state=present
    regexp='preserve hostname'
    line='preserve hostname: true'"

- name: Set IPv4 address into hosts file
  lineinfile:
    dest=/etc/hosts
    create=yes
    state=present
    regexp='{{ ansible_default_ipv4.address }}.*{{ ansible_hostname }}'
    line='{{ ansible_default_ipv4.address }} {{ ansible_hostname }}'

- name: Set LC_ALL locale in global environment
  lineinfile:
    dest=/etc/environment
    create=yes
    state=present
    regexp='LC_ALL'
    line='LC_ALL=en_US.UTF-8'

- name: Add X-road user
  user: name={{ xroad_superuser }} password={{ xroad_superuser_password }} update_password=on_create

- name: Add X-Road repositories
  copy: src=xroad.list dest=/etc/apt/sources.list.d/xroad.list owner=root group=root mode=0644

- name: Add X-Road apt key
  apt_key: url=http://x-road.eu/.test/xroad6/xroad_repo.gpg state=present

- name: Add additional X-Road apt key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x00A6F0A3C300EE8C state=present

- name: Add additional X-Road apt key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xEB9B1D8886F44E2A state=present

- name: Add superuser username to X-Road configuration
  debconf:
    name: 'xroad-proxy'
    question: 'xroad-common/username'
    value: '{{ xroad_superuser }}'
    vtype: 'string'

- name: Add FQDN to X-Road admin Web UI configuration
  debconf:
    name: 'xroad-proxy'
    question: 'xroad-common/admin-subject'
    value: '/CN={{ xroad_admin_fqdn }}'
    vtype: 'string'

- name: Add alternative DNs to X-Road admin Web UI configuration
  debconf:
    name: 'xroad-proxy'
    question: 'xroad-common/admin-altsubject'
    value: '{{ xroad_admin_dn_s }}'
    vtype: 'string'

- name: Add FQDN to X-Road service configuration
  debconf:
    name: 'xroad-proxy'
    question: 'xroad-common/service-subject'
    value: '/CN={{ xroad_service_fqdn }}'
    vtype: 'string'

- name: Add alternative DNs to X-Road service configuration
  debconf:
    name: 'xroad-proxy'
    question: 'xroad-common/service-altsubject'
    value: '{{ xroad_service_dn_s }}'
    vtype: 'string'

- name: Install X-Road package and its dependencies
  apt:
    update_cache: yes
    name: xroad-proxy
    state: present

- name: Install alternative Web UI certificate
  lineinfile:
    dest:  "/etc/nginx/sites-enabled/default-sdsb"
    regexp: "ssl_certificate "
    line: "        ssl_certificate {{ internal_ssl_cert }};"
  when: nginx_ssl_cert is defined
  notify: restart nginx

- name: Install alternative Web UI certificate
  lineinfile:
    dest:  "/etc/nginx/sites-enabled/default-sdsb"
    regexp: "ssl_certificate_key"
    line: "        ssl_certificate_key {{ internal_ssl_key }};"
  when: nginx_ssl_key is defined
  notify: restart nginx

- name: Workaround to service utility potentially not stopping nginx
  command: killall nginx
  notify: restart nginx
